// RideRash — the surface library. EVERY MAP HERE IS GENERATED BY CODE.
//
// WHAT CHANGED, AND WHY. This module used to load seven 1024² JPEGs that had
// been generated by an image API and committed into `assets/tex/`. Nothing in
// the 404 asset contract forbade that — the contract binds *asset modules*
// (`assets/*.js`), and this is ordinary game code — but the project's whole
// thesis is "3D as code: no mesh files, no downloads", and 3.3 MB of committed
// PNGs is a file dependency in a project built to have none. There was a
// concrete cost too, not just a philosophical one: the loader had a non-fatal
// missing-texture path, so a copy of the folder without `assets/tex/` silently
// reverted the road to flat colour and nothing said so.
//
// So the maps are now built at load time from a seed, and the only image files
// left in the game are the two sky panoramas (see below). Same public API, so
// `level.js` and `world.js` did not have to be rewritten around it.
//
// THE ONE REMAINING FILE, DECLARED. `assets/tex/sky_day.jpg` and
// `sky_dusk.jpg` are still real images. They are equirectangular photographic
// panoramas, `DynamicSky` blends them and measures the sun's direction out of
// them, and no procedural generator in this project can produce that. This is a
// knowing, bounded deviation: two files, sky only, nothing structural.
//
// WHERE EACH MAP COMES FROM. Two generators, split on whether the sanctioned
// recipe library already covers the material:
//
//   surfaces.js (harness, sanctioned)  plaster · concrete(stone) · rail(metal)
//   RR_RECIPES  (below, game code)     asphalt · scrub · kerb
//
// The harness recipes are used as-is so the level and the coded assets share one
// surface vocabulary — and one texture cache, since `applySurfaces` asks for the
// same recipes at the same 512 px size. The three road materials have no
// harness recipe, and two of them need per-channel colour (scrub's olive/dust
// mix, the kerb's hazard banding) which the harness recipes' scalar tint cannot
// express, so they are authored here.
//
// WHAT THIS BUYS BEYOND COMPLIANCE. The JPEG path had a colour map and a normal
// derived from its luminance, and no roughness map at all — so the road's gloss
// was one number across the whole carriageway. Every generated set here carries
// a real roughness map built from the same height field as the normal, which is
// what gives the wet deck a broken specular rather than a uniform sheen. See
// `RR_RECIPES.asphalt`: water sits in the hollows, so the hollows are the smooth
// part, and that inversion is the whole effect.
import * as THREE from 'three';
import { surface, RECIPES } from '../surfaces.js';

const BASE = './assets/tex/';

// ---------------------------------------------------------------------------
// Deterministic noise. Same construction as surfaces.js, duplicated rather than
// imported because the harness module exports its recipes and its builder but
// not its primitives, and a local copy is cheaper than patching a file that is
// meant to stay a verbatim copy of the harness original.
// ---------------------------------------------------------------------------
function makeNoise(seed = 1) {
  const P = new Uint8Array(512);
  let s = seed >>> 0 || 1;
  const rnd = () => (s = (s * 1664525 + 1013904223) >>> 0) / 4294967296;
  const perm = [...Array(256).keys()];
  for (let i = 255; i > 0; i--) { const j = (rnd() * (i + 1)) | 0; [perm[i], perm[j]] = [perm[j], perm[i]]; }
  for (let i = 0; i < 512; i++) P[i] = perm[i & 255];
  const fade = (t) => t * t * t * (t * (t * 6 - 15) + 10);
  const lp = (a, b, t) => a + (b - a) * t;
  const grad = (h, x, y) => ((h & 1) ? -x : x) + ((h & 2) ? -y : y);
  return (x, y) => {
    const X = Math.floor(x) & 255, Y = Math.floor(y) & 255;
    const xf = x - Math.floor(x), yf = y - Math.floor(y);
    const u = fade(xf), v = fade(yf);
    const aa = P[P[X] + Y], ab = P[P[X] + Y + 1], ba = P[P[X + 1] + Y], bb = P[P[X + 1] + Y + 1];
    return lp(lp(grad(aa, xf, yf), grad(ba, xf - 1, yf), u),
              lp(grad(ab, xf, yf - 1), grad(bb, xf - 1, yf - 1), u), v);
  };
}
function fbm(n, x, y, octaves = 5, lac = 2.07, gain = 0.5) {
  let a = 1, f = 1, sum = 0, norm = 0;
  for (let i = 0; i < octaves; i++) { sum += a * n(x * f, y * f); norm += a; a *= gain; f *= lac; }
  return sum / norm;
}
const clamp01 = (v) => (v < 0 ? 0 : v > 1 ? 1 : v);
const mix = (a, b, t) => a + (b - a) * t;

// ---------------------------------------------------------------------------
// Game-local recipes.
//
// Same declarative shape as the harness recipes — a height field, plus how
// colour and roughness follow it — with one difference: `shade` returns an RGB
// triple instead of a scalar, because a verge that is olive in the clumps and
// tan in the dirt is a large part of what stops the midground reading as one
// flat sheet of cardboard.
//
// ALBEDO IS A TINT MULTIPLIER, NOT A COLOUR. Every value here is around 1.0 and
// the material keeps its own palette — the same convention the harness uses, and
// the reason one asphalt map serves a wet coast road and a dusty canyon one. It
// also matters for the frame metrics: a photographic albedo multiplies the
// material's hue toward the photo's own grey, which is exactly how the old maps
// flattened the verge. A near-neutral tint map leaves the driven tint's chroma
// intact. Values above 1.0 clip (the buffer is 8-bit), so author in 0.5–1.0 and
// let the material colour carry the brightness.
//
// `rough` is likewise a MODULATION, centred near 1.0, because three.js
// multiplies `material.roughness` by the map. The absolute gloss level stays on
// the material where the surface driver can lerp it per frame; the map only
// supplies the breakup. `roughMean` (computed below) compensates the material
// scalar for the map's average so a requested 0.52 still renders as 0.52.
// ---------------------------------------------------------------------------
const RR_RECIPES = {
  // Tarmac: coarse aggregate, tar patches with soft edges, and hairline cracks.
  // Tiled once per 7.5 m by the road's world-space UVs (see level.js), which
  // puts the aggregate at roughly 1 cm on screen — the difference between
  // tarmac and gravel is entirely in this number.
  // MEASURED AND RETUNED. The first pass ran bump 1.0 with a crack depth of
  // 0.55 at frequency 5, and the road rendered as crumpled foil -- broad
  // meandering channels catching the sun like water ripples, nothing like
  // tarmac. Three numbers caused it and all three are here: the cracks were
  // deep, they were LOW FREQUENCY (so they read as channels rather than as
  // hairlines), and the normal strength amplified both. Tarmac's relief is
  // almost entirely aggregate at a scale of one centimetre; the cracks are
  // supposed to be visible as lines, not felt as terrain.
  asphalt: {
    seed: 1301, tile: 7.5, bump: 0.42, size: 512,
    height: (n, x, y) => {
      const grit = fbm(n, x * 46, y * 46, 4) * 0.5 + 0.5;        // the stones
      const stones = Math.pow(grit, 1.5);
      const patch = fbm(n, x * 3.1 + 17, y * 3.1, 3) * 0.5 + 0.5; // laid in strips
      // Cracks are a ridge function: the ZERO crossings of a mid-frequency
      // field, which is what makes them lines rather than blotches.
      const cr = 1 - Math.min(1, Math.abs(fbm(n, x * 13 + 61, y * 13, 4)) * 30);
      const crack = Math.pow(clamp01(cr), 2.2);
      return clamp01(stones * 0.62 + patch * 0.38 - crack * 0.22);
    },
    shade: (h, n, x, y) => {
      // Stones read slightly lighter than the binder; the patches are darker
      // and very slightly warm, because fresh tar is.
      const t = 0.66 + h * 0.34;
      const patch = Math.pow(clamp01(fbm(n, x * 3.1 + 17, y * 3.1, 3) * 0.5 + 0.5), 2.4);
      return [mix(t, 0.54, patch * 0.7), mix(t, 0.52, patch * 0.7), mix(t, 0.53, patch * 0.7)];
    },
    rough: (h) => {
      // THE WET-ROAD INVERSION. Water collects in the LOW places, and water is
      // smooth, so the hollows must be the glossy part and the proud aggregate
      // the matt part. Doing it the intuitive way round (rough in the hollows)
      // gives a road that looks dusty however much gloss you add to it.
      //
      // The band was 0.55..1.0 and the sun's reflection blew out to pure white.
      // Gridding the frame (harness/_blown.mjs) put 33% of ONE cell over 245 --
      // left of centre, at the horizon, where the view angle is most grazing and
      // a GGX lobe stretches furthest -- and zero in the sky. Bloom was the
      // amplifier and is now gentler; this narrows the lobe underneath it.
      // The smear survives, which matters: critic round 2 named a matte road as
      // the biggest remaining defect in the frame.
      // 0.80 still left a hard white blob: gridding the frame put 28.6% of one
      // cell over 245 -- left of centre, at the horizon, where the view angle
      // is most grazing. 0.87 keeps the smear reading as wet tarmac and stops
      // it clipping. The whole-frame figure is 1.9% against a bar of 1.1%.
      return mix(0.87, 1.0, Math.pow(h, 0.8));
    },
  },

  // Dry roadside scrub over dirt. Two hues, deliberately: the clumps are olive
  // and the ground between them is warm dust, and the boundary between them is
  // most of what makes a verge read as ground cover rather than as paint.
  scrub: {
    seed: 1607, tile: 2.2, bump: 0.9, size: 384,
    height: (n, x, y) => {
      const clump = fbm(n, x * 9, y * 9, 5) * 0.5 + 0.5;
      const blade = fbm(n, x * 38, y * 38, 2) * 0.5 + 0.5;
      return clamp01(Math.pow(clump, 1.7) * 0.8 + blade * 0.2);
    },
    shade: (h, n, x, y) => {
      const green = clamp01((h - 0.28) * 2.1);      // the proud parts are alive
      const t = 0.62 + h * 0.34;
      // olive over dust: the green channel is held up and the blue pulled down
      return [mix(t * 1.04, t * 0.80, green), mix(t * 0.96, t * 0.94, green), mix(t * 0.74, t * 0.52, green)];
    },
    rough: (h) => mix(0.92, 1.0, h),
  },

  // Kerb stone with weathered hazard banding. Shape and colour only — the style
  // lock forbids glyphs anywhere, and a band is a shape.
  kerb: {
    seed: 1913, tile: 1.6, bump: 0.7, size: 256,
    height: (n, x, y) => {
      const stone = fbm(n, x * 7, y * 7, 5) * 0.5 + 0.5;
      const chip = Math.pow(clamp01(fbm(n, x * 21 + 9, y * 21, 3) * 0.5 + 0.5), 6) * 0.7;
      return clamp01(stone - chip);
    },
    shade: (h, n, x, y) => {
      // Bands run along the kerb. `band` is 1 inside a painted stripe, and the
      // paint is worn through wherever the stone beneath is chipped away.
      const band = (Math.floor(y * 6) & 1) ? 1 : 0;
      const wear = clamp01(fbm(n, x * 11, y * 11, 3) * 0.5 + 0.5);
      const paint = band * clamp01(wear * 1.3);
      const t = 0.74 + h * 0.3;
      return [mix(t, 0.98, paint), mix(t, 0.40, paint), mix(t, 0.30, paint)];
    },
    rough: (h) => mix(0.88, 1.0, h),
  },
};

// ---------------------------------------------------------------------------
// The builder. Height field -> albedo + roughness + normal, all three agreeing
// with each other by construction, all three tileable (the normal's central
// difference wraps).
// ---------------------------------------------------------------------------
function heightToNormal(h, size, strength) {
  const out = new Uint8ClampedArray(size * size * 4);
  const at = (x, y) => h[((y + size) % size) * size + ((x + size) % size)];
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    const dx = (at(x + 1, y) - at(x - 1, y)) * strength;
    const dy = (at(x, y + 1) - at(x, y - 1)) * strength;
    const len = Math.hypot(dx, dy, 1);
    const i = (y * size + x) * 4;
    out[i] = ((-dx / len) * 0.5 + 0.5) * 255;
    out[i + 1] = ((-dy / len) * 0.5 + 0.5) * 255;
    out[i + 2] = ((1 / len) * 0.5 + 0.5) * 255;
    out[i + 3] = 255;
  }
  return out;
}

function canvasTexture(data, size, srgb) {
  const c = document.createElement('canvas');
  c.width = c.height = size;
  c.getContext('2d').putImageData(new ImageData(data, size, size), 0, 0);
  const t = new THREE.CanvasTexture(c);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.anisotropy = 8;
  t.generateMipmaps = true;
  t.minFilter = THREE.LinearMipmapLinearFilter;
  t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  return t;
}

function buildLocal(name) {
  const r = RR_RECIPES[name];
  const size = Math.round(r.size * TEX_SCALE);
  const n = makeNoise(r.seed);
  const hf = new Float32Array(size * size);
  const alb = new Uint8ClampedArray(size * size * 4);
  const rgh = new Uint8ClampedArray(size * size * 4);
  let roughSum = 0;

  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    const u = x / size, v = y / size;
    const h = clamp01(r.height(n, u, v));
    hf[y * size + x] = h;
    const [cr, cg, cb] = r.shade(h, n, u, v);
    const rv = clamp01(r.rough(h, n, u, v));
    roughSum += rv;
    const i = (y * size + x) * 4;
    alb[i] = clamp01(cr) * 255; alb[i + 1] = clamp01(cg) * 255; alb[i + 2] = clamp01(cb) * 255; alb[i + 3] = 255;
    const rb = rv * 255;
    rgh[i] = rb; rgh[i + 1] = rb; rgh[i + 2] = rb; rgh[i + 3] = 255;
  }

  return {
    map: canvasTexture(alb, size, true),
    roughnessMap: canvasTexture(rgh, size, false),
    normalMap: canvasTexture(heightToNormal(hf, size, r.bump * 2.4), size, false),
    tileMeters: r.tile,
    roughMean: roughSum / (size * size),
  };
}

// ---------------------------------------------------------------------------
// The public names the rest of the game asks for, and where each is built.
//
// The names are the ones the JPEG era used, kept deliberately: they are what
// level.js and world.js say, they describe the SURFACE rather than the
// generator, and renaming twenty call sites to prove a point would have been
// the change most likely to break something.
// ---------------------------------------------------------------------------
const SOURCES = {
  wet_asphalt: { from: 'local', recipe: 'asphalt' },
  dry_scrub:   { from: 'local', recipe: 'scrub' },
  kerb_stripe: { from: 'local', recipe: 'kerb' },
  plaster:     { from: 'harness', recipe: 'plaster' },
  concrete:    { from: 'harness', recipe: 'stone' },
  metal_rail:  { from: 'harness', recipe: 'metal' },
};

// name -> { map, roughnessMap, normalMap, tileMeters, roughMean }
const SETS = {};
// flat lookup used by getTexture: 'concrete', 'concrete_n', 'concrete_r', skies
const TEX = {};

// The mean of a harness recipe's roughness band, read off the recipe itself.
// `surface()` writes `mix(rough[1], rough[0], h)` per texel, so the average over
// a height field that is itself roughly centred is the band's midpoint. Close
// enough to compensate with, and it costs no second pass over the pixels.
function harnessRoughMean(recipe) {
  const band = RECIPES[recipe] && RECIPES[recipe].rough;
  return band ? (band[0] + band[1]) / 2 : 1;
}

// Yield to the browser between recipes so the loading bar actually paints.
// Generating six surfaces is one to two seconds of straight-line JS and without
// this the page freezes on 2% and then jumps to done, which reads as a hang.
const breathe = () => new Promise((res) => setTimeout(res, 0));

/**
 * Build every surface, then load the two sky panoramas. Keeps the old name and
 * the old progress callback so main.js's init order is untouched.
 */
// LOW / MOBILE generates every surface at half size: a quarter of the texture
// memory (the maps are tiled and seen at speed; half resolution is not missed).
let TEX_SCALE = 1;
export async function loadTextures(onProgress, scale = 1) {
  TEX_SCALE = scale;
  const names = Object.keys(SOURCES);
  const total = names.length + 1;   // + the skies, loaded as one step
  let done = 0;

  for (const name of names) {
    const src = SOURCES[name];
    try {
      const set = src.from === 'local'
        ? buildLocal(src.recipe)
        : { ...surface(THREE, src.recipe, Math.round(512 * TEX_SCALE)), roughMean: harnessRoughMean(src.recipe) };
      SETS[name] = set;
      TEX[name] = set.map;
      TEX[`${name}_n`] = set.normalMap;
      TEX[`${name}_r`] = set.roughnessMap;
    } catch (e) {
      // A generator that throws must not blank the game: the material keeps its
      // flat colour, exactly as a missing file used to. Unlike a missing file,
      // this one cannot happen from a bad copy of the folder.
      console.warn(`[riderash] surface failed: ${name}`, e);
      SETS[name] = null; TEX[name] = null;
    }
    done++;
    if (onProgress) onProgress(done / total, name);
    await breathe();
  }

  await loadSkies();
  if (onProgress) onProgress(1, 'sky');
  return TEX;
}

// THE ONLY FILE LOADS LEFT IN THE GAME. Equirectangular panoramas for
// DynamicSky, which blends them and derives the sun direction from the image
// itself. Declared as a deviation in HANDOFF.md §4.2; everything else on screen
// is generated above.
async function loadSkies() {
  const l = new THREE.TextureLoader();
  l.setCrossOrigin('anonymous');
  await Promise.all(['sky_day', 'sky_dusk'].map((name) => new Promise((res) => {
    l.load(`${BASE}${name}.jpg`,
      (t) => {
        t.colorSpace = THREE.SRGBColorSpace;
        t.mapping = THREE.EquirectangularReflectionMapping;
        TEX[name] = t;
        res();
      },
      undefined,
      () => {
        // Non-fatal, and the fallback is real: level.js builds a horizon band
        // when `sky_dusk` is absent, and DynamicSky reports `ok === false`.
        console.warn(`[riderash] sky panorama missing: ${name}`);
        TEX[name] = null;
        res();
      });
  })));
}

export function getTexture(name) { return TEX[name] || null; }

/** The whole generated set for a surface, maps plus its roughness mean. */
export function getSurfaceSet(name) { return SETS[name] || null; }

// Cloned per (name, repeat), NOT per material.
//
// Texture repeat lives on the texture, so two materials wanting different
// densities need different texture objects — but cloning per MATERIAL would
// make a GPU upload for each of the town's five wall colours and three roof
// colours, for maps that are pixel-identical. Keying the clone on the repeat
// instead collapses those eight to two. (assetlib merges by material VALUES and
// a texture's uuid is part of that comparison, so this also keeps the bake's
// buckets from fragmenting — see surfaces.js on why texel density normally
// belongs in the UVs.)
const _clones = new Map();
function repeated(set, rx, ry) {
  const key = `${set.map.uuid}|${rx}|${ry}`;
  const hit = _clones.get(key);
  if (hit) return hit;
  const out = {};
  for (const k of ['map', 'roughnessMap', 'normalMap']) {
    if (!set[k]) { out[k] = null; continue; }
    if (rx === 1 && ry === 1) { out[k] = set[k]; continue; }
    const t = set[k].clone();
    t.repeat.set(rx, ry);
    t.needsUpdate = true;
    out[k] = t;
  }
  _clones.set(key, out);
  return out;
}

/**
 * Build a standard material from a named surface. `repeat` is tiles per UV
 * unit; on the road strips the UVs are already world-space so it stays 1.
 *
 * ROUGHNESS COMPENSATION. three.js multiplies `material.roughness` by the
 * roughness map, so attaching a map whose mean is 0.83 silently makes every
 * surface 17% glossier than the number written here — and on the rail, whose
 * band runs down to 0.24, considerably more than that. The requested value is
 * therefore divided by the map's mean. `roughGain` is stashed on the material so
 * the surface driver can apply the same correction when it re-drives roughness
 * from the world spine every frame.
 */
export function texMaterial(name, opts = {}) {
  const {
    repeat = 1, repeatY = null, color = 0xffffff,
    roughness = 0.85, metalness = 0.05,
    normalScale = 1.0, envIntensity = null,
    useNormal = true, useRough = true,
  } = opts;

  const set = SETS[name];
  const m = new THREE.MeshStandardMaterial({ color, roughness, metalness });

  if (set) {
    const rx = repeat, ry = repeatY ?? repeat;
    const maps = repeated(set, rx, ry);
    m.map = maps.map;
    if (useNormal && maps.normalMap) {
      m.normalMap = maps.normalMap;
      m.normalScale = new THREE.Vector2(normalScale, normalScale);
    }
    if (useRough && maps.roughnessMap) {
      m.roughnessMap = maps.roughnessMap;
      const gain = 1 / Math.max(0.12, set.roughMean);
      m.userData.roughGain = gain;
      m.roughness = Math.min(1, roughness * gain);
    }
  }

  if (envIntensity !== null) {
    // see lighting.js: the material must carry its OWN envMap or three.js 0.169
    // silently overrides the intensity with the scene value.
    m.userData.wantEnv = envIntensity;
  }
  return m;
}

// The skies are not installed as a flat background. Both panoramas are handed to
// DynamicSky (sky.js), which blends them live and derives the sun's direction
// from the image. This function exists only to sample the horizon colour for the
// fog, which must match whatever the sky is doing.
export function skyHorizonColour(prefer = 'sky_dusk') {
  const t = getTexture(prefer) || getTexture('sky_day');
  const img = t && t.image;
  if (!img || !img.width) return 0xa8b4bc;
  try {
    const W = 64, H = 64;
    const c = document.createElement('canvas');
    c.width = W; c.height = H;
    const g = c.getContext('2d', { willReadFrequently: true });
    g.drawImage(img, 0, 0, W, H);
    const d = g.getImageData(0, 0, W, H).data;
    const rows = [Math.floor(H * 0.50), Math.floor(H * 0.53), Math.floor(H * 0.56)];
    const samples = [];
    for (const y of rows) {
      for (let x = 0; x < W; x++) {
        const i = (y * W + x) * 4;
        samples.push([d[i], d[i + 1], d[i + 2], d[i] * 0.2126 + d[i + 1] * 0.7152 + d[i + 2] * 0.0722]);
      }
    }
    samples.sort((a, b) => a[3] - b[3]);
    const keep = samples.slice(0, Math.max(1, Math.floor(samples.length * 0.75)));
    let r = 0, gg = 0, b = 0;
    for (const s of keep) { r += s[0]; gg += s[1]; b += s[2]; }
    r /= keep.length; gg /= keep.length; b /= keep.length;
    return (Math.round(r) << 16) | (Math.round(gg) << 8) | Math.round(b);
  } catch (e) {
    return 0xa8b4bc;
  }
}
